name: microbosh-azure

logging:
  level: debug
  file: /tmp/run.log

network:
  type: manual
  ip: 10.0.0.5
  cloud_properties:
    virtual_network_name: boshvnet-crp
    subnet_name: BOSH
    tcp_endpoints:
    - "22:22"
    - "53:53"
    - "4222:4222"
    - "6868:6868"
    - "25250:25250"
    - "25555:25555"
    - "25777:25777"
    udp_endpoints:
    - "68:68"

resources:
  persistent_disk: 50000
  cloud_properties:
    instance_type: Standard_A1

cloud:
  plugin: azure
  properties:
    azure:
      environment: AzureCloud
      api_version: 2015-05-01-preview
      subscription_id: Your subscription id
      storage_account_name: Your storage account name
      storage_access_key: The access key of your storage account
      resource_group_name: Your resource group name
      client_id: Your client id of the service principle
      client_secret: Your client secret of the service principle
      tenant_id: Your tenant id of the service principle
      ssh_certificate: |
        -----BEGIN CERTIFICATE-----
        MIIDXTCCAkWgAwIBAgIJAKzcDgjYCuoQMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
        BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQwHhcNMTUwMTI2MDkxNTEwWhcNMTYwMTI2MDkxNTEwWjBF
        MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
        ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAoRvYPvbldVTi1csRu3WsmjklMZHcnWWExvcEOahU4aNYfx5HfoKyQ7EW
        14rqL/qzZhTrX0iLvgtE7Jjh6VVoX3X2YInGwh1DkeHyhMS5f8/NvtcVO6xwR6fi
        jGmRYuR6OLhyQwOoIoxtjX/40cT5Lcj9yMCiDtNEhZCy86Q4KFo15qz2ZYNL4ThC
        pKbCo6sIl+BhsIv/ECtmt9j7paJlrZA1Z0HqSd7fpEZ0d1VIy1foGx3M4Z7BUdon
        Zw8kiEv5zzYdRCeN5ZeNe7pCzHcIZmPbq3RNfC+5DLXbHpXP9ga0J+QrcmfiLfiN
        A5KFGHdJKj7tSEoqBqNVrgEX0V9B/QIDAQABo1AwTjAdBgNVHQ4EFgQUYd72B08a
        336kO2QCLtIMZZABCtAwHwYDVR0jBBgwFoAUYd72B08a336kO2QCLtIMZZABCtAw
        DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEARe2/bewgdLVcc7H1JVP7
        uBMHx9wUbtdO+XodlwzKghGKv22erGNNNuOX6JdMaKI1dmXOd3FzH8wwcHas1T2f
        O8MkKx8EcyIIiK4ubj0ZDilSB2Ia9FF0Mh3XsoU3nq+Shjyw6SoGjZn1Op3ivJVR
        57mnITzK1o1FN1b93/CSke1VrwhApVhduvbzqaCTPCdkUPTSxufGHzczDZHCVub2
        kJXeUGBfDRYJiLStVpMcTYbQ5DAPokJPdbV1XZ+eMFCoJBGJmywhzZa3MVkirB+f
        y4+8P1lLemO/DLu+/CGRLXXo8MNaC4v1rSuSvEOlBbyWyeij71uc9/sCUi8Er2kj
        lg==
        -----END CERTIFICATE-----

      ssh_private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAoRvYPvbldVTi1csRu3WsmjklMZHcnWWExvcEOahU4aNYfx5H
        foKyQ7EW14rqL/qzZhTrX0iLvgtE7Jjh6VVoX3X2YInGwh1DkeHyhMS5f8/NvtcV
        O6xwR6fijGmRYuR6OLhyQwOoIoxtjX/40cT5Lcj9yMCiDtNEhZCy86Q4KFo15qz2
        ZYNL4ThCpKbCo6sIl+BhsIv/ECtmt9j7paJlrZA1Z0HqSd7fpEZ0d1VIy1foGx3M
        4Z7BUdonZw8kiEv5zzYdRCeN5ZeNe7pCzHcIZmPbq3RNfC+5DLXbHpXP9ga0J+Qr
        cmfiLfiNA5KFGHdJKj7tSEoqBqNVrgEX0V9B/QIDAQABAoIBAGgqPa2wKnmrMaJz
        Unq2watRSVf8a/ykN64A5g11ZbQhzcUaybTlQeb8Z71ixrnQyQ82dVw85oUwehbT
        XjVkEECwX2TZj9XP3/FBenEXVKxrqiY6oDLd8haSWKraUrLy8Icd0lq70YjM7MQx
        Oqo+RbGxo0yaJ+2X8VS+UsWuptSHQCgaVvppLFBMietcjmZomAGfidTQeKOypyE6
        ELeOn1RAglPDdZTvlMKiIHvTI7TE87nzEcs1l0aKlD5CQmgIXZ7vgFjsBFdIVjOh
        vL5XFem9k27F/G8ipIbyNlR0ogGZy2iXFIjcKQIuBq89mWZPuGyd0ZJ53sLavcyl
        +NQb/E0CgYEA1SwRzUpF7UDF5n1vL76U+sNM+YcIpXxRCZhGSDtCEeEIEAVS8fwT
        mvxVP7QMLmGgDqH/hqXYwLkcpBh0CnTJHYVJHqg4zfvxlv+fmsDgKZ93KAkKHdk/
        UWpc2pjPTzNECyKgLp0CzEajELoz6MU0lORQtAPt8OgoMkCFwTQCggsCgYEAwXoJ
        ZRIUa+QmS40wqebEB+625gAKtXaE8utILy39FTuq753qZPWZFrC7v91SLjMfWEla
        0AQiWd3EKPM63IjuQ4mgoh87bYchUSOQqhY8UtAQBQ4DSmZjzqClQE45KEfHdQrh
        nJ2dYb9kj2BbKDNUf41iBYZvMsPWCsmo29lnmRcCgYBbZp3ra+E3rQItpbK6wfiW
        3I5wnxlx+y+z8XqRFfdqOxZ96Ap8fxzY40CaI9TlPi6ml4c8cHfTiothQKrgoNpq
        se98GZzhlRktKUWB0RlMP3eTzuxrh+7CNdzCTar1xoFyVNJhqii89byNO4luUMAO
        5yZDSTwIg0JY6ZlwEaDRqQKBgAvmdLN5xDXKp6xX99lLb11JiohlEkONEapbXGpC
        euGWdPIeFW+2R39EyZeIhmh/DnuAr4xB5NcAM/OM2l78MSOIUJAIOcCH4j26YUiE
        65rwXzvgW8V0vMjVyrRE23El0Rfa3nuimi6L9iR3ecPkPFtIF/JdDXPi5cRuGOvE
        2IFrAoGBAIWeeQbJ53xeJsfzqfvN7PWEAMzTg5GmUeS2RHceP4Oo6VP2xU2DvN0A
        Pmdxa+kdShoaI8dWUfV1nzANlorD/5pLrkrP3EhSfqwDmkiwXsrBjCO+Zj+P3rKJ
        vzUItkeJUb9f/dLsVw3+bzSHlbDYqWWxkwTiWsaswoxZYPrOIH2S
        -----END RSA PRIVATE KEY-----

apply_spec:
  agent:
    blobstore: {address: 10.0.0.5}
    nats:{address: 10.0.0.5}
  properties:
    registry:{address: 10.0.0.5}

